# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RNbfIOacACtgoeyJL7xAaGNMWLOR64Jo
"""

import io
from pypdf import PdfReader
from docx import Document


def extract_pdf_text(file):
    reader = PdfReader(file)
    text = ""

    for page in reader.pages:
        page_text = page.extract_text()

        if page_text:
            text += page_text + "\n"

    return text


def extract_docx_text(file):
    document = Document(file)

    text = []

    for paragraph in document.paragraphs:
        if paragraph.text.strip():
            text.append(paragraph.text)

    return "\n".join(text)


def extract_txt_text(file):
    return file.read().decode("utf-8")


def extract_resume_text(file):
    file_type = file.name.lower()

    if file_type.endswith(".pdf"):
        return extract_pdf_text(file)

    elif file_type.endswith(".docx"):
        return extract_docx_text(file)

    elif file_type.endswith(".txt"):
        return extract_txt_text(file)

    else:
        raise ValueError(
            "Unsupported file format. Please upload PDF, DOCX, or TXT."
        )